// <auto-generated />
using BandDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandDB.Migrations
{
    [DbContext(typeof(BandDBContext))]
    partial class BandDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandDB.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.HasKey("ArtistId");

                    b.HasIndex("BandId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BandId = 1,
                            FirstName = "Spencer",
                            LastName = "Hopps"
                        },
                        new
                        {
                            ArtistId = 2,
                            BandId = 1,
                            FirstName = "Bull",
                            LastName = "Frog"
                        },
                        new
                        {
                            ArtistId = 3,
                            BandId = 2,
                            FirstName = "Ben",
                            LastName = "Folds"
                        },
                        new
                        {
                            ArtistId = 4,
                            BandId = 2,
                            FirstName = "Darren",
                            LastName = "Jesse"
                        },
                        new
                        {
                            ArtistId = 5,
                            BandId = 2,
                            FirstName = "Robert",
                            LastName = "Sledge"
                        });
                });

            modelBuilder.Entity("BandDB.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("BandId");

                    b.HasIndex("GenreId");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            BandId = 1,
                            GenreId = 2,
                            Name = "The Frogs"
                        },
                        new
                        {
                            BandId = 2,
                            GenreId = 3,
                            Name = "Ben Folds Five"
                        });
                });

            modelBuilder.Entity("BandDB.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Jazz"
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Metal"
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Rock"
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Pop"
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Country"
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Rap"
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Punk"
                        });
                });

            modelBuilder.Entity("BandDB.Models.Artist", b =>
                {
                    b.HasOne("BandDB.Models.Band", "Band")
                        .WithMany("Artists")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BandDB.Models.Band", b =>
                {
                    b.HasOne("BandDB.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
